name: Deliver to DockerHub
on:
  push:
  pull_request:
  release:
    types: [published]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: dart format --set-exit-if-changed .
      - name: Generate mocks
        run: flutter pub run build_runner build
      - name: Lint
        run: flutter analyze
      - name: Test
        run: flutter test
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        run: |
          echo "RENAISSANCE_MAN_BUILD_VERSION=$(python get_app_version.py)" >> $GITHUB_ENV
      - name: Check version
        run: |
          echo RENAISSANCE_MAN_BUILD_VERSION
          echo ${{ env.RENAISSANCE_MAN_BUILD_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          tags: kostaleonard/renaissance-man-app:latest,kostaleonard/renaissance-man-app:${{ env.RENAISSANCE_MAN_BUILD_VERSION }}
          outputs: type=docker,dest=/tmp/renaissance_man.tar
          cache-from: type=gha
          cache-to: type=gha
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: renaissance-man-image
          path: /tmp/renaissance_man.tar
  trivy-scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: renaissance-man-image
          path: .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          input: '/github/workspace/renaissance_man.tar'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
  deliver:
    needs: [trivy-scan]
    runs-on: ubuntu-latest
    # TODO only on release
    #if: github.event_name == 'release'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: kostaleonard
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # These build steps use the cached images according to docker/build-push-action docs.
      # We want to use the cached images so that we don't build twice.
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kostaleonard/renaissance-man-app:latest,kostaleonard/renaissance-man-app:${{ env.RENAISSANCE_MAN_BUILD_VERSION }}
          cache-from: type=gha
          cache-to: type=gha
